### ISSUE TITLE
Route not found on my server

### ISSUE THREAD

**Issue by markond** [zkrati/router#1]
When I use router on localhost everything works great. But when I deploy it on server it starts to throw RouteNotFoundException exception.

**Comment by zkrati** [comment]
Hello, could you please dump $_SERVER['REQUEST_URI'] and $_SERVER['PHP_SELF'] and post the result?

**Comment by markond** [comment]
It says: 

/var/www/html/web/lib/components/index.php
/v1/add

**Comment by zkrati** [comment]
Should be fixed in next version. We are already testing fix ;-)
Thank you!
